name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Github-Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen 1.10.0
      run: |
        mkdir -p ~/Downloads/Install_Files/Doxygen
        cd ~/Downloads/Install_Files/Doxygen
        wget https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.linux.bin.tar.gz
        tar -xf doxygen-1.10.0.linux.bin.tar.gz
        cd doxygen-1.10.0
        sudo make
        sudo make install
        doxygen --version

    - name: Copy custom CSS
      run: |
        mkdir -p html/doxygen-awesome-css
        cp -r docs/doxygen-awesome-css/* html/doxygen-awesome-css

    - name: Generate Doxygen Documentation
      run: doxygen docs/Doxyfile

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
